In [2]:

import numpy as np
import pandas as pd
df = pd.read_csv("SBUX.csv", index_col = "Date", parse_dates=True)

In [3]:

df.head(5)

Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2019-12-11  86.260002  86.870003  85.849998  86.589996  82.458740   4921900
2019-12-12  88.000000  88.889999  87.540001  88.209999  84.001442  10282100
2019-12-13  88.019997  88.790001  87.580002  88.669998  84.439499   6714100
2019-12-16  89.139999  89.300003  88.430000  88.779999  84.544258   6705600
2019-12-17  88.870003  88.970001  87.470001  88.129997  83.925278   7296900

In [6]:
X = df.iloc[:, :-1]
y = df.iloc[:, 5:6] 

In [28]:
y

Volume
Date                
2019-12-11   4921900
2019-12-12  10282100
2019-12-13   6714100
2019-12-16   6705600
2019-12-17   7296900
...              ...
2020-12-04   6952700
2020-12-07   4514800
2020-12-08   3911300
2020-12-09   6629900
2020-12-10  12939200

[253 rows x 1 columns]

In [7]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
mm = MinMaxScaler()
ss = StandardScaler()


X_ss = ss.fit_transform(X)
y_mm = mm.fit_transform(y) 

In [29]:
X_ss

array([[0.46501033, 0.43644414, 0.51542403, 0.49614696, 0.39551766],
       [0.6539359 , 0.66267575, 0.69038876, 0.67120687, 0.56533628],
       [0.65610714, 0.65147637, 0.69453003, 0.72091504, 0.61355702],
       ...,
       [1.99704658, 2.08278598, 1.98139854, 2.07600605, 2.14690117],
       [2.16751399, 2.15446335, 1.99071576, 1.98847658, 2.06023962],
       [2.33798151, 2.58900775, 2.26506846, 2.52770302, 2.59411436]])

In [8]:
#first 200 for training

X_train = X_ss[:200, :]
X_test = X_ss[200:, :]

y_train = y_mm[:200, :]
y_test = y_mm[200:, :] 

In [9]:
print("Training Shape", X_train.shape, y_train.shape)
print("Testing Shape", X_test.shape, y_test.shape) 

Training Shape (200, 5) (200, 1)
Testing Shape (53, 5) (53, 1)


In [32]:
X_train

array([[ 0.46501033,  0.43644414,  0.51542403,  0.49614696,  0.39551766],
       [ 0.6539359 ,  0.66267575,  0.69038876,  0.67120687,  0.56533628],
       [ 0.65610714,  0.65147637,  0.69453003,  0.72091504,  0.61355702],
       [ 0.77771476,  0.70859458,  0.78252968,  0.73280192,  0.62508876],
       [ 0.74839912,  0.67163566,  0.68314171,  0.66256174,  0.55695225],
       [ 0.69628123,  0.65819579,  0.71937685,  0.64743324,  0.54227358],
       [ 0.63547785,  0.62907659,  0.69453003,  0.70470572,  0.59783107],
       [ 0.73971266,  0.67499543,  0.72662379,  0.69822224,  0.59154327],
       [ 0.72125461,  0.65819579,  0.75664737,  0.67336854,  0.56743416],
       [ 0.67565119,  0.63019678,  0.73801211,  0.70470572,  0.59783107],
       [ 0.7331982 ,  0.6481166 ,  0.71627107,  0.65715921,  0.55170909],
       [ 0.6658796 ,  0.61451744,  0.70591825,  0.66256174,  0.55695225],
       [ 0.6550219 ,  0.58539824,  0.64069441,  0.58799986,  0.48461987],
       [ 0.59313242,  0.56187918,  0.6

In [10]:
import torch #pytorch
import torch.nn as nn
from torch.autograd import Variable 

In [11]:
X_train_tensors = Variable(torch.Tensor(X_train))
X_test_tensors = Variable(torch.Tensor(X_test))

y_train_tensors = Variable(torch.Tensor(y_train))
y_test_tensors = Variable(torch.Tensor(y_test)) 

In [33]:
X_train_tensors

tensor([[ 0.4650,  0.4364,  0.5154,  0.4961,  0.3955],
        [ 0.6539,  0.6627,  0.6904,  0.6712,  0.5653],
        [ 0.6561,  0.6515,  0.6945,  0.7209,  0.6136],
        [ 0.7777,  0.7086,  0.7825,  0.7328,  0.6251],
        [ 0.7484,  0.6716,  0.6831,  0.6626,  0.5570],
        [ 0.6963,  0.6582,  0.7194,  0.6474,  0.5423],
        [ 0.6355,  0.6291,  0.6945,  0.7047,  0.5978],
        [ 0.7397,  0.6750,  0.7266,  0.6982,  0.5915],
        [ 0.7213,  0.6582,  0.7566,  0.6734,  0.5674],
        [ 0.6757,  0.6302,  0.7380,  0.7047,  0.5978],
        [ 0.7332,  0.6481,  0.7163,  0.6572,  0.5517],
        [ 0.6659,  0.6145,  0.7059,  0.6626,  0.5570],
        [ 0.6550,  0.5854,  0.6407,  0.5880,  0.4846],
        [ 0.5931,  0.5619,  0.6666,  0.6399,  0.5349],
        [ 0.6670,  0.7142,  0.7432,  0.7944,  0.6848],
        [ 0.7256,  0.6862,  0.7484,  0.7382,  0.6303],
        [ 0.6659,  0.6089,  0.6831,  0.6626,  0.5570],
        [ 0.6496,  0.5664,  0.6479,  0.6334,  0.5286],
        [ 

In [12]:
#reshaping to rows, timestamps, features

X_train_tensors_final = torch.reshape(X_train_tensors,   (X_train_tensors.shape[0], 1, X_train_tensors.shape[1]))


X_test_tensors_final = torch.reshape(X_test_tensors,  (X_test_tensors.shape[0], 1, X_test_tensors.shape[1])) 

In [34]:
X_train_tensors_final

tensor([[[ 0.4650,  0.4364,  0.5154,  0.4961,  0.3955]],

        [[ 0.6539,  0.6627,  0.6904,  0.6712,  0.5653]],

        [[ 0.6561,  0.6515,  0.6945,  0.7209,  0.6136]],

        [[ 0.7777,  0.7086,  0.7825,  0.7328,  0.6251]],

        [[ 0.7484,  0.6716,  0.6831,  0.6626,  0.5570]],

        [[ 0.6963,  0.6582,  0.7194,  0.6474,  0.5423]],

        [[ 0.6355,  0.6291,  0.6945,  0.7047,  0.5978]],

        [[ 0.7397,  0.6750,  0.7266,  0.6982,  0.5915]],

        [[ 0.7213,  0.6582,  0.7566,  0.6734,  0.5674]],

        [[ 0.6757,  0.6302,  0.7380,  0.7047,  0.5978]],

        [[ 0.7332,  0.6481,  0.7163,  0.6572,  0.5517]],

        [[ 0.6659,  0.6145,  0.7059,  0.6626,  0.5570]],

        [[ 0.6550,  0.5854,  0.6407,  0.5880,  0.4846]],

        [[ 0.5931,  0.5619,  0.6666,  0.6399,  0.5349]],

        [[ 0.6670,  0.7142,  0.7432,  0.7944,  0.6848]],

        [[ 0.7256,  0.6862,  0.7484,  0.7382,  0.6303]],

        [[ 0.6659,  0.6089,  0.6831,  0.6626,  0.5570]],

        [[ 0.6

In [13]:
print("Training Shape", X_train_tensors_final.shape, y_train_tensors.shape)
print("Testing Shape", X_test_tensors_final.shape, y_test_tensors.shape) 

Training Shape torch.Size([200, 1, 5]) torch.Size([200, 1])
Testing Shape torch.Size([53, 1, 5]) torch.Size([53, 1])


In [14]:
class LSTM1(nn.Module):
    def __init__(self, num_classes, input_size, hidden_size, num_layers, seq_length):
        super(LSTM1, self).__init__()
        self.num_classes = num_classes #number of classes
        self.num_layers = num_layers #number of layers
        self.input_size = input_size #input size
        self.hidden_size = hidden_size #hidden state
        self.seq_length = seq_length #sequence length

        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size,
                          num_layers=num_layers, batch_first=True) #lstm
        self.fc_1 =  nn.Linear(hidden_size, 128) #fully connected 1
        self.fc = nn.Linear(128, num_classes) #fully connected last layer

        self.relu = nn.ReLU()
    
    def forward(self,x):
        h_0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size)) #hidden state
        c_0 = Variable(torch.zeros(self.num_layers, x.size(0), self.hidden_size)) #internal state
        # Propagate input through LSTM
        output, (hn, cn) = self.lstm(x, (h_0, c_0)) #lstm with input, hidden, and internal state
        hn = hn.view(-1, self.hidden_size) #reshaping the data for Dense layer next
        out = self.relu(hn)
        out = self.fc_1(out) #first Dense
        out = self.relu(out) #relu
        out = self.fc(out) #Final Output
        return out

In [15]:
num_epochs = 1000 #1000 epochs
learning_rate = 0.001 #0.001 lr

input_size = 5 #number of features
hidden_size = 2 #number of features in hidden state
num_layers = 1 #number of stacked lstm layers

num_classes = 1 #number of output classes 

In [16]:
lstm1 = LSTM1(num_classes, input_size, hidden_size, num_layers, X_train_tensors_final.shape[1]) #our lstm class 

In [17]:
criterion = torch.nn.MSELoss()    # mean-squared error for regression
optimizer = torch.optim.Adam(lstm1.parameters(), lr=learning_rate)

In [20]:
for epoch in range(num_epochs):
    outputs = lstm1.forward(X_train_tensors_final) #forward pass
    optimizer.zero_grad() #caluclate the gradient, manually setting to 0
 
  # obtain the loss function
    loss = criterion(outputs, y_train_tensors)
 
    loss.backward() #calculates the loss of the loss function
 
    optimizer.step() #improve from loss, i.e backprop
    if epoch % 100 == 0:
        print("Epoch: %d, loss: %1.5f" % (epoch, loss.item())) 

Epoch: 0, loss: 0.12505
Epoch: 100, loss: 0.02644
Epoch: 200, loss: 0.02006
Epoch: 300, loss: 0.01818
Epoch: 400, loss: 0.01712
Epoch: 500, loss: 0.01550
Epoch: 600, loss: 0.01328
Epoch: 700, loss: 0.01147
Epoch: 800, loss: 0.01083
Epoch: 900, loss: 0.01060


In [21]:
df_X_ss = ss.transform(df.iloc[:, :-1]) #old transformers
df_y_mm = mm.transform(df.iloc[:, -1:]) #old transformers

df_X_ss = Variable(torch.Tensor(df_X_ss)) #converting to Tensors
df_y_mm = Variable(torch.Tensor(df_y_mm))
#reshaping the dataset
df_X_ss = torch.reshape(df_X_ss, (df_X_ss.shape[0], 1, df_X_ss.shape[1])) 

In [25]:
%matplotlib inline
import matplotlib as plt

train_predict = lstm1(df_X_ss)#forward pass
data_predict = train_predict.data.numpy() #numpy conversion
dataY_plot = df_y_mm.data.numpy()

data_predict = mm.inverse_transform(data_predict) #reverse transformation
dataY_plot = mm.inverse_transform(dataY_plot)
plt.figure(figsize=(10,6)) #plotting
plt.axvline(x=200, c='r', linestyle='--') #size of the training set

plt.plot(dataY_plot, label='Actuall Data') #actual plot
plt.plot(data_predict, label='Predicted Data') #predicted plot
plt.title('Time-Series Prediction')
plt.legend()
plt.show() 

TypeError: 'module' object is not callable